from typing import List, Optional
from pydantic import BaseModel, Field

class LiteraturePlan(BaseModel):
    """Plan generated by the planner node."""
    topic: str = Field(description="The main topic of research.")
    keywords: List[str] = Field(description="Keywords to search for.")
    min_year: int = Field(description="Minimum year for papers.")
    need_author_stats: bool = Field(description="Whether to check author statistics/reputation.")

class Paper(BaseModel):
    """Represents a single research paper."""
    title: str
    authors: List[str]
    summary: str
    year: int

class AuthorStats(BaseModel):
    """Statistics about authors."""
    top_authors: List[str]
    average_h_index: float
    note: str

class LiteratureSummary(BaseModel):
    """Final output summary."""
    main_trends: List[str] = Field(description="Key trends identified in the papers.")
    notable_papers: List[Paper] = Field(description="List of significant papers found.")
    open_questions: List[str] = Field(description="Unanswered questions or future directions.")
    conclusion: str = Field(description="Overall conclusion of the review.")
